### ISSUE TITLE
Trojan:AndroidOS/ZkarletFlash from Windows Defender on Win10 when trying to download version 1.3.1

### ISSUE THREAD

**Issue by p8wer** [pivotiiii/nsui_banner_fixer#1]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AAndroidOS%2FZkarletFlash&threatid=2147785565

I'm getting this virus warning from Windows Defender when trying to download the latest 1.3.1 release. If I try downloading the 1.3 release, no such issue ocurrs.

![image](https://github.com/pivotiiii/nsui_banner_fixer/assets/31834469/ec88f11d-4502-4011-8204-fb11647a86ef)

![image](https://github.com/pivotiiii/nsui_banner_fixer/assets/31834469/0097a152-a9e5-47d6-bd90-5dde4c65d043)

**Comment by pivotiiii** [comment]
Weirdly enough I get that too. It hasn't been an issue before though. Seems like quite a few anti virus programs do not like packaged python apps. I submitted the latest version to Microsoft, maybe that helps. In the meantime, if you don't trust the packaged program, you could try running the python script directly after taking a look at the latest 2 commits. The only thing that changed where some additional errors I forgot to handle when the wrong kinds of file are being passed in.

Edit: So it seems that the file should not be falsely detected anymore once your malware definitions for Windows Defender update. This can also be done manually:

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"
