### ISSUE TITLE
Title Version is set to "0.0.0" after fixing the banner

### ISSUE THREAD

**Issue by UberLuu** [pivotiiii/nsui_banner_fixer#4]
After using nsui_banner_fixer v1.3.1 the major/minor/micro version get all set to 0.

I guess this could be fixed by adding the [relevant arguments](https://github.com/3DSGuy/Project_CTR/blob/master/makerom/README.md#:~:text=%2Dmajor%20%3Cversion%3E,micro%20for%20the%20title.) in [this line](https://github.com/pivotiiii/nsui_banner_fixer/blob/master/src/main.py#L112) if the major/minor/micro version can be obtained from the original cia file.

**Comment by pivotiiii** [comment]
Hey thanks for pointing this out, I just uploaded a new version that carries over the version information :)
