### ISSUE TITLE
Can't Download - Virus Detected

### ISSUE THREAD

**Issue by AmyNapsALot** [pivotiiii/nsui_banner_fixer#5]
Browser won't let me download the .exe file, get the message "Virus Detected". Tried in both Chrome and Edge, turning off security settings, but nothing works.

**Comment by AmyNapsALot** [comment]
Managed to work out the python (eventually) and got that to work.

**Comment by pivotiiii** [comment]
Yeah it is an issue with the way the program is packaged. It extracts the Python runtime on first launch, which most protection software finds highly suspicious. I am currently working on a new version written in C++ instead of Python, that should fix it. I'll let you know once I release it.

**Comment by pivotiiii** [comment]
Hey, I just uploaded the C++ version, which should hopefully not be falsely flagged as a threat anymore. You can get it [here](https://github.com/pivotiiii/nsui_banner_fixer/releases/tag/v2.0.0).
