### ISSUE TITLE
Program immediately closes when I enter anything

### ISSUE THREAD

**Issue by IceTMDAbss** [pivotiiii/nsui_banner_fixer#6]
I can't do anything because the moment I press a button the program shuts down instantly. Is there any fix to this? 

Thank you.

**Comment by pivotiiii** [comment]
Have you followed the usage instructions? What does the folder you run the program in look like?

**Comment by IceTMDAbss** [comment]
Hi,

-I downloaded the latest release of the nsui_banner_fixer.exe 1.4.1 folder.

-I extracted all the files.

-I opened the "nsui_banner_fixer" program below the "tools" folder.

-The program opens normally.

-Whenever I try to type anything, it automatically closes.

Did I miss anything? I'm on Windows 10 if it matters.

**Comment by pivotiiii** [comment]
Please take a look at the [instructions](https://github.com/pivotiiii/nsui_banner_fixer?tab=readme-ov-file#usage). Just put the .cia files you want to fix in the same folder and run it again.
